version: '3'
services:
  traefik_proxy:
    container_name: TraefikProxy
    restart: unless-stopped
    image: traefik:latest
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - '/home/traefik/traefik.yml:/etc/traefik/traefik.yml'
      # - '/home/traefik/data:/data'
