version: '3'

services:

  traefik_proxy:
    container_name: TraefikProxy
    restart: unless-stopped
    image: traefik:latest
    environment:
      CF_API_EMAIL: 'YOUR@EMAIL.COM'
      CF_DNS_API_TOKEN: 'YOUR_CLOUDFLARE_TOKEN'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /home/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    container_name: WhoAmI
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.noofny.me`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=noofny_certs"
